import React, { useState } from "react";
import { useLocation } from "react-router-dom";
import { Badge } from "../../components/ui/Badge";
import { Card } from "../../components/ui/Card";

export function LegalPages() {
  const location = useLocation();
  const isPrivacy = location.pathname.includes("privacy");
  const title = isPrivacy ? "Privacy Policy" : "Terms of Service";
  const lastUpdated = "July 1, 2026";

  const sections = isPrivacy
    ? [
        { id: "s1", title: "1. Information We Collect", body: "Everline collects information provided directly by users during registration, campaign setup, and website intelligence inputs. This includes names, work emails, domain URLs, company names, and custom marketing instructions." },
        { id: "s2", title: "2. How We Use Information", body: "We use collected information solely to operate our multi-agent pipeline, generate campaign copy, perform website structure audits, and provide technical support. We do not sell user data to third parties." },
        { id: "s3", title: "3. Data Isolation & AI Models", body: "Proprietary inputs, generated content briefs, and website telemetry are never used to train public LLM models. All inference requests are routed through enterprise zero-data-retention APIs." },
        { id: "s4", title: "4. Data Retention & Erasure", body: "Users may request complete deletion of their account data and campaign histories at any time through our support portal or directly within account settings." },
      ]
    : [
        { id: "s1", title: "1. Acceptance of Terms", body: "By accessing or using the Everline Platform, you agree to be bound by these Terms of Service and all applicable laws and regulations." },
        { id: "s2", title: "2. Platform License & Use", body: "Subject to compliance with these terms, Everline grants you a non-exclusive, non-transferable right to access and use the platform for your internal business operations." },
        { id: "s3", title: "3. Intellectual Property Rights", body: "All content, diagrams, whitepapers, and copy generated by your account using the Everline multi-agent pipeline belong exclusively to your organization upon human approval." },
        { id: "s4", title: "4. Limitation of Liability", body: "Everline shall not be liable for indirect, incidental, or consequential damages resulting from platform downtime or reliance on generated content without human review." },
      ];

  return (
    <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-12 text-left font-sans">
      <div className="max-w-3xl space-y-3 mb-10">
        <Badge variant="accent">Legal & Compliance</Badge>
        <h1 className="text-3xl font-bold text-ink tracking-tight">{title}</h1>
        <p className="text-xs font-mono text-ink-subtle">Last Updated: {lastUpdated}</p>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-12 gap-10">
        {/* Main Document Content */}
        <div className="lg:col-span-8 space-y-8 max-w-[68ch]">
          {sections.map((s) => (
            <div key={s.id} id={s.id} className="space-y-2 border-b border-border pb-6">
              <h2 className="text-base font-bold text-ink font-mono">{s.title}</h2>
              <p className="text-xs sm:text-sm text-ink-muted leading-relaxed">{s.body}</p>
            </div>
          ))}
        </div>

        {/* TOC Sidebar */}
        <aside className="hidden lg:block lg:col-span-4">
          <div className="sticky top-24 p-5 bg-raise border border-border rounded-card space-y-3">
            <h3 className="text-xs font-mono uppercase tracking-wider text-ink-subtle">Document Contents</h3>
            <ul className="space-y-2 text-xs font-mono text-ink-muted">
              {sections.map((s) => (
                <li key={s.id}>
                  <a href={`#${s.id}`} className="hover:text-accent transition-colors">
                    {s.title}
                  </a>
                </li>
              ))}
            </ul>
          </div>
        </aside>
      </div>
    </div>
  );
}
