import React, { useState } from "react";
import { useNavigate } from "react-router-dom";
import { Button } from "../../components/ui/Button";
import { Badge } from "../../components/ui/Badge";
import { Card } from "../../components/ui/Card";
import { CheckCircle2, ChevronDown, ChevronRight, HelpCircle } from "lucide-react";

export function PricingPage() {
  const navigate = useNavigate();
  const [billingCycle, setBillingCycle] = useState("annual"); // 'monthly' | 'annual'
  const [openFaq, setOpenFaq] = useState(0);

  const tiers = [
    {
      name: "Starter",
      monthlyPrice: "$490",
      annualPrice: "$390",
      target: "For early-stage growth teams & niche B2B products.",
      popular: false,
      features: [
        "5 Campaign Runs / month",
        "10 AI Marketing Agents",
        "2 Website Intelligence Audits / month",
        "Human Approval Gate Workflow",
        "Standard Export (PDF / Markdown)",
        "Email Support (24h SLA)",
      ],
      cta: "Start Free Trial",
    },
    {
      name: "Growth",
      monthlyPrice: "$1,490",
      annualPrice: "$1,190",
      target: "For scaling B2B SaaS teams shipping 20+ assets per month.",
      popular: true,
      features: [
        "25 Campaign Runs / month",
        "10 AI Marketing Agents + Trend Telemetry",
        "10 Website Intelligence Audits / month",
        "5-Area Business Gap Engine",
        "Automated RSS Monitoring Signals",
        "Multi-Format Copy & SVG Diagrams",
        "Priority Support (4h SLA)",
      ],
      cta: "Book a Demo",
    },
    {
      name: "Enterprise",
      monthlyPrice: "Custom",
      annualPrice: "Custom",
      target: "For multi-brand enterprises & high-volume agencies.",
      popular: false,
      features: [
        "Unlimited Campaign Runs & Audits",
        "Dedicated Custom Agent Fine-Tuning",
        "Custom RSS & Competitor Feeds",
        "Single Sign-On (SSO / SAML)",
        "Dedicated Solutions Architect",
        "Custom SLA & Security Reviews",
      ],
      cta: "Talk to Enterprise",
    },
  ];

  const comparisonRows = [
    { name: "Monthly Campaign Runs", starter: "5", growth: "25", enterprise: "Unlimited" },
    { name: "10-Agent Pipeline Access", starter: "Yes", growth: "Yes", enterprise: "Yes" },
    { name: "Website Intelligence Audits", starter: "2 / mo", growth: "10 / mo", enterprise: "Unlimited" },
    { name: "Automated RSS Signals", starter: "No", growth: "Yes", enterprise: "Yes (Custom Feeds)" },
    { name: "5-Area Gap Engine", starter: "Basic", growth: "Full Audit", enterprise: "Full + Custom Metrics" },
    { name: "Multi-Format Copywriting", starter: "Blogs & LinkedIn", growth: "All 8 Formats", enterprise: "All + Custom Templates" },
    { name: "Architecture SVG Diagrams", starter: "Standard", growth: "Advanced", enterprise: "Custom Brand Design" },
    { name: "Single Sign-On (SSO)", starter: "No", growth: "No", enterprise: "Included" },
    { name: "Support SLA", starter: "24-hour Email", growth: "4-hour Priority", enterprise: "1-hour Dedicated SLA" },
  ];

  const faqs = [
    {
      q: "Can I switch between Monthly and Annual billing?",
      a: "Yes, you can upgrade or switch billing cycles at any time. When switching to annual, the two-month discount applies automatically to your remaining period.",
    },
    {
      q: "What happens when I reach my monthly campaign run limit?",
      a: "Additional runs can be purchased on-demand for $40 per run on Starter or $30 on Growth, or you can upgrade to the next tier seamlessly.",
    },
    {
      q: "Is there a free trial available?",
      a: "Yes! We offer a 14-day full access trial for growth teams. No credit card is required to set up your account and execute your first campaign run.",
    },
    {
      q: "How does the Human Approval Gate work?",
      a: "No asset generated by our 10-agent pipeline is published or exported without explicit human sign-off. You can approve, reject, or request revisions on every item.",
    },
  ];

  return (
    <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-12 space-y-16 text-left font-sans">
      {/* Header */}
      <div className="text-center max-w-2xl mx-auto space-y-4">
        <Badge variant="accent">Transparent Pricing</Badge>
        <h1 className="text-3xl sm:text-4xl font-bold text-ink tracking-tight">
          Simple, Predictable Plans for Modern Growth Teams
        </h1>
        <p className="text-xs sm:text-sm text-ink-muted leading-relaxed">
          Scale your autonomous marketing pipeline without hidden usage surcharges.
        </p>

        {/* Monthly / Annual Toggle */}
        <div className="pt-2 flex items-center justify-center gap-3">
          <div className="inline-flex p-1 bg-raise border border-border rounded-control gap-1">
            <button
              onClick={() => setBillingCycle("monthly")}
              className={`px-4 py-1.5 text-xs font-medium rounded-control transition-colors ${
                billingCycle === "monthly" ? "bg-surface text-ink shadow-sm font-semibold" : "text-ink-muted hover:text-ink"
              }`}
            >
              Monthly Billing
            </button>
            <button
              onClick={() => setBillingCycle("annual")}
              className={`px-4 py-1.5 text-xs font-medium rounded-control transition-colors flex items-center gap-1.5 ${
                billingCycle === "annual" ? "bg-surface text-ink shadow-sm font-semibold" : "text-ink-muted hover:text-ink"
              }`}
            >
              <span>Annual Billing</span>
              <span className="px-1.5 py-0.5 rounded text-[10px] font-mono bg-accent-tint text-accent font-bold">2 Months Free</span>
            </button>
          </div>
        </div>
      </div>

      {/* Pricing Cards Grid */}
      <div className="grid grid-cols-1 md:grid-cols-3 gap-8 items-stretch">
        {tiers.map((tier) => {
          const price = billingCycle === "annual" ? tier.annualPrice : tier.monthlyPrice;
          return (
            <Card
              key={tier.name}
              className={`p-6 flex flex-col justify-between space-y-6 relative transition-all duration-150 ${
                tier.popular
                  ? "border-accent bg-accent-tint/10 shadow-sm"
                  : "border-border bg-surface"
              }`}
            >
              {tier.popular && (
                <div className="absolute -top-3 left-1/2 -translate-x-1/2">
                  <span className="px-3 py-0.5 rounded-full bg-accent text-white text-[10px] font-mono font-bold uppercase tracking-wider">
                    Most Popular
                  </span>
                </div>
              )}

              <div className="space-y-4">
                <div className="space-y-1">
                  <h3 className="text-lg font-bold text-ink">{tier.name}</h3>
                  <p className="text-xs text-ink-muted min-h-[36px]">{tier.target}</p>
                </div>

                <div className="font-mono">
                  <span className="text-3xl font-bold text-ink">{price}</span>
                  {price !== "Custom" && <span className="text-xs text-ink-subtle"> / month</span>}
                </div>

                <div className="pt-4 border-t border-border space-y-2.5">
                  <span className="text-[10px] font-mono uppercase tracking-wider text-ink-subtle block">What's Included:</span>
                  {tier.features.map((feat, i) => (
                    <div key={i} className="flex items-start gap-2 text-xs text-ink">
                      <CheckCircle2 className="w-4 h-4 text-accent shrink-0 mt-0.5" />
                      <span>{feat}</span>
                    </div>
                  ))}
                </div>
              </div>

              <Button
                variant={tier.popular ? "primary" : "secondary"}
                onClick={() => navigate("/demo")}
                className="w-full"
              >
                {tier.cta}
              </Button>
            </Card>
          );
        })}
      </div>

      {/* Feature Comparison Table */}
      <div className="space-y-4">
        <div className="space-y-1">
          <h2 className="text-xl font-bold text-ink tracking-tight">Full Plan Feature Comparison</h2>
          <p className="text-xs text-ink-muted">Detailed side-by-side capabilities breakdown.</p>
        </div>

        <div className="border border-border rounded-card overflow-hidden bg-surface">
          <table className="w-full text-left text-xs">
            <thead>
              <tr className="bg-raise border-b border-border font-mono text-[11px] text-ink-muted">
                <th className="p-3.5 font-semibold">Capability</th>
                <th className="p-3.5 font-semibold">Starter</th>
                <th className="p-3.5 font-semibold text-accent">Growth</th>
                <th className="p-3.5 font-semibold">Enterprise</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-border">
              {comparisonRows.map((row, i) => (
                <tr key={i} className="hover:bg-raise/40 transition-colors">
                  <td className="p-3.5 font-medium text-ink">{row.name}</td>
                  <td className="p-3.5 font-mono text-ink-muted">{row.starter}</td>
                  <td className="p-3.5 font-mono font-semibold text-accent">{row.growth}</td>
                  <td className="p-3.5 font-mono text-ink">{row.enterprise}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>

      {/* Pricing FAQ Accordion */}
      <div className="space-y-4 max-w-3xl mx-auto">
        <div className="text-center space-y-1">
          <h2 className="text-xl font-bold text-ink tracking-tight">Frequently Asked Questions</h2>
          <p className="text-xs text-ink-muted">Everything you need to know about plans and billing.</p>
        </div>

        <div className="space-y-2">
          {faqs.map((faq, idx) => {
            const isOpen = openFaq === idx;
            return (
              <Card
                key={idx}
                className="p-4 cursor-pointer hover:border-border-strong transition-colors space-y-2 bg-surface border-border"
                onClick={() => setOpenFaq(isOpen ? null : idx)}
              >
                <div className="flex items-center justify-between">
                  <h3 className="text-xs font-semibold text-ink flex items-center gap-2">
                    <HelpCircle className="w-4 h-4 text-accent shrink-0" />
                    <span>{faq.q}</span>
                  </h3>
                  <ChevronDown className={`w-4 h-4 text-ink-subtle transition-transform ${isOpen ? "rotate-180" : ""}`} />
                </div>
                {isOpen && (
                  <p className="text-xs text-ink-muted leading-relaxed pl-6 pt-1 border-t border-border/60">
                    {faq.a}
                  </p>
                )}
              </Card>
            );
          })}
        </div>
      </div>
    </div>
  );
}
